### ISSUE TITLE
client certificate-based access

### ISSUE THREAD

**Issue by xingchen966** [daltoniam/Starscream#436] opened 2017-12-05 09:06 UTC
The WebSocket does not seem to solve the situation where server need a client certificate.
In WebSocket.swift, It just validates the server certificate, but does not validate the client certificate.

**Comment by daltoniam** [comment] 2017-12-08 19:38
This is a duplicate of #271. This feature has not been added. PR is welcomed.

**Closed by daltoniam** 2017-12-08 19:38 UTC

**Comment by jarrillaga** [comment] 2018-01-15 18:57
@xingchen966 Did you solve this ?
