### ISSUE TITLE
When connecting to a wss:// socket, getting an SSL handshake error

### ISSUE THREAD

**Issue by yuriymacdev** [daltoniam/Starscream#726] opened 2020-01-21 01:13 UTC
The same host with a different WebSock Swift framework (https://github.com/tidwall/SwiftWebSocket) connects just fine.
Am I missing some extra configuration?

Error printout:
```
[BoringSSL] boringssl_context_handle_fatal_alert(1872) [C1.1:1][0x7fcec6701630] write alert, level: fatal, description: certificate unknown
[BoringSSL] boringssl_context_error_print(1862) boringssl ctx 0x6000000d40a0: 140526066114904:error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-283.60.3/ssl/handshake.cc:369:
[BoringSSL] boringssl_session_handshake_error_print(111) [C1.1:1][0x7fcec6701630] 140526066114904:error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-283.60.3/ssl/handshake.cc:369:
[BoringSSL] nw_protocol_boringssl_handshake_negotiate_proceed(726) [C1.1:1][0x7fcec6701630] handshake failed at state 12288
error: Optional(-9858: Optional(handshake failed))
```
Code that triggers the SSL handshake error:
```
websock = WebSocket(request: URLRequest(url: URL(string: "wss://myhost:9110/")!))
websock.delegate = self
websock.connect()

    func didReceive(event: WebSocketEvent, client: WebSocket) {
        switch event {
        case .connected(let headers):
            print("websocket is connected: \(headers)")
        case .disconnected(let reason, let code):
            print("websocket is disconnected: \(reason) with code: \(code)")
        case .text(let string):
            print("Received text: \(string)")
        case .binary(let data):
            print("Received data: \(data.count)")
        case .ping(_):
            break
        case .pong(_):
            break
        case .viablityChanged(_):
            break
        case .reconnectSuggested(_):
            break
        case .cancelled:
            print("cancelled")
        case .error(let error):
            print("error: \(String(describing: error))")
        }
    }
```

**Comment by eduardvasilache** [comment] 2020-01-24 11:11
I have the exact same issue.
It works when I try to connect to `wss://echo.websocket.org`, but it doesn't work when I try to connect to our server, which is created using Amazon API Gateway.
It works with [SwiftWebSocket](https://github.com/tidwall/SwiftWebSocket) and it works on Android with [Scarlet](https://github.com/Tinder/Scarlet).
Any thoughts?

**Comment by application-developer-DA** [comment] 2020-01-24 17:54
Same issue here. I downgraded to 3.1.1 and the problem is gone, but I can reproduce it on 4.0.0, so I tried to figure out what was the difference between version, the git-diff is quite big, so I did not check all the changes in the source code, but I've noticed this commit https://github.com/daltoniam/Starscream/commit/a986e38e563af99a6b0149ba20162692cb1aecec. I went to `excon`'s changelog to figure out if there was a certificate/TLS-related change there and noticed:

```
0.70.0 2019-12-02
=================

Update bundled certificates
```

This might be somehow related to this issue, but I'm not 100% sure about that (the rest of the changes between 3.1.1 and 4.0.0 need to be checked as well).

**Comment by UltraNemesis** [comment] 2020-01-27 12:55
Facing same issue myself.

**Comment by arrabidas92** [comment] 2020-02-04 06:13
Facing same issue also on my iOS project.

**Comment by my-mo** [comment] 2020-02-04 15:33
Same here any fix coming?

**Comment by application-developer-DA** [comment] 2020-02-04 19:25
Well, there is [a quick fix](https://github.com/daltoniam/Starscream/issues/726#issuecomment-578233596) (or rather a workaround / kludge, not really a fix).

**Comment by arrabidas92** [comment] 2020-02-05 05:33
But the issue if I downgrade there is a fatal error on Xcode 11.

**Comment by fassko** [comment] 2020-02-05 16:34
I will check this in coming days.

Folks can you please tell which iOS, tvOS, iPadOS version are you using to run it?

**Comment by arrabidas92** [comment] 2020-02-05 20:02
iOS : 13.1.3
iPhone 6s

**Comment by matteogervasi** [comment] 2020-02-06 08:59
@arrabidas92 you probably need to Clean Build Folder after downgrading..

**Comment by tomgekeerd** [comment] 2020-02-06 21:34
Seems like v4.0.0 has a default value set for certificate pinning when initialising `WebSocket`, so it always tries to pin a certificate by default, even if you don't have one.

```
public convenience init(request: URLRequest, certPinner: CertificatePinning? = FoundationSecurity(), compressionHandler: CompressionHandler? = nil)
```

Passing `nil` to `certPinner:` disables it and allows you to successfully make a connection. Like so:

```
WebSocket(request: urlRequest, certPinner: nil)
```

**Comment by kamrankhan07** [comment] 2020-02-12 04:29
Passing nil to `certPinner` will not work as `allowSelfSigned` is set to false. Here is how I did it

`WebSocket(request: encodedRequest, certPinner: FoundationSecurity(allowSelfSigned: true))`

**Comment by sonrohan** [comment] 2020-02-29 01:50
Neither `certPinner: FoundationSecurity(allowSelfSigned: true)` or `certPinner: nil` works for me, does anyone have an idea?
```

        var request = URLRequest(url: URL(string: "wss://10.246.32.18:6868")!)
        request.timeoutInterval = 5
       
        socket = WebSocket(request: request, certPinner: FoundationSecurity(allowSelfSigned: true))
        socket.delegate = self
        socket.connect()
        
        socket.write(string: "Hello from the other side!")
      
```

**Comment by tapz** [comment] 2020-03-17 14:18
> FoundationSecurity(allowSelfSigned: true)

This is only required if you use a self signed certificate. With properly signed certificates nil value works just fine.

**Comment by daltoniam** [comment] 2020-04-04 20:20
Looks like y'all got this sorted out, so I'm gonna go ahead and close this issue. Also version 4.0.1 was released today with a few SSL pinning fixes in the FoundationSecurity class

**Closed by daltoniam** 2020-04-04 20:20 UTC

**Comment by kwei94** [comment] 2021-08-16 08:52
Hi, I tried with version 4.00, 4.0.4, 3.0.0, 3.1.1 pod install..
all not worked for me. 
Here returned with connections refused. 

<img width="710" alt="Screen Shot 2021-08-16 at 4 50 55 PM" src="https://user-images.githubusercontent.com/53994150/129537359-a4d7f827-69e5-4a55-b022-b9dcdac75e26.png">
<img width="815" alt="Screen Shot 2021-08-16 at 4 51 08 PM" src="https://user-images.githubusercontent.com/53994150/129537390-9ef1fbd9-d11e-433f-ab45-34c1a6ef2065.png">
