### ISSUE TITLE
Client certificate support

### ISSUE THREAD

**Issue by AdamMak** [daltoniam/Starscream#411] opened 2017-10-19 09:37 UTC
Is it possible to use client certificates with star scream? In my project, this is required, so I was wondering if there was any information regarding support for this 

Thanks in advance

**Comment by daltoniam** [comment] 2017-11-16 19:30
This is a duplicate of #271. This feature has not been added. PR is welcomed.

**Closed by daltoniam** 2017-11-16 19:30 UTC

**Comment by jarrillaga** [comment] 2018-01-15 18:57
@AdamMak Did you solve this issue ?
