### ISSUE TITLE
Using with System Proxy on Simulator

### ISSUE THREAD

**Issue by kevinmlong** [daltoniam/Starscream#240] opened 2016-08-25 02:11 UTC
It seems that when using this framework on a simulator (I've been using it for a while now, but never on the simulator), the connection request ignores the system proxy. Other network requests (e.g. REST API calls using Alamofire) are handled appropriately and routed through the proxy. IS there a way to set the proxy for this framework or have others experienced this issue?

**Comment by acmacalister** [comment] 2016-09-01 00:09
I haven't heard of any issues with proxies. I would assume since proxies are suppose to be transparent and we are relying the Apple networking APIs just like AlamoFire does, it should work fine.

**Comment by kevinmlong** [comment] 2016-09-03 02:09
So, after hours of exploring, researching, and testing, I've got it working with the following:

```swift
//WebSocket.swift
//This was already here
inputStream = readStream!.takeRetainedValue()
outputStream = writeStream!.takeRetainedValue()
//Added code below        
let proxyDict = CFNetworkCopySystemProxySettings()
let socksConfig = CFDictionaryCreateMutableCopy(nil, 0, proxyDict!.takeRetainedValue());
        
CFWriteStreamSetProperty(outputStream, kCFStreamPropertySOCKSProxy, socksConfig);
CFReadStreamSetProperty(inputStream, kCFStreamPropertySOCKSProxy, socksConfig);
```
This picks up the system wide proxy settings. Additionally, it seems that it only observes the SOCKS proxy setting. I've been able to get it working by running Charles Proxy on the host machine with External Proxy settings only set for HTTP/HTTPS.

**Comment by daltoniam** [comment] 2016-09-14 02:36
Ah great work and thanks for taking the time to figure this out. Seems like the system proxy settings should be already be applied to the NSStream, but Cocoa APIs 😄. I'll make sure to look at this when I do the Swift 3 stuff. Thanks again.

**Comment by ergunkocak** [comment] 2017-10-11 09:16
Is this implemented?

**Comment by skerkewitz** [comment] 2017-10-12 11:59
The above code may run on the simulator (I didn't check TBH) but will not work on a real iOS device. The reason is that you can not specify a SOCK5 server in the iOS setting. Therefore `CFNetworkCopySystemProxySettings()` will return a dictionary that only contains HTTP proxy information.

Unfortunately the HTTP proxy is completely useless in this case as it will be ignore (you would have to create the socket using `CFReadStreamCreateForHTTPRequest()` (which is deprecated by the ways) as far as I understand it.

I think the easiest and simplest solution for everybody would be if you could set the sock5 proxy information on the WebSocket instand yourself before you call `connect()`. Somewhat like this:

```
        self.webSocket = WebSocket(url: encodedURLRequest.url!)
        self.webSocket!.delegate = self
        self.webSocket!.setSocks5ProxyInformation(host: "192.168.1.4", port: "8889")
        self.webSocket!.useSocks5Proxy = true
        self.webSocket!.connect()
```

If will create a pull request if I find the time.

**Comment by daltoniam** [comment] 2017-12-09 04:04
3.0.2 released with #423!

**Closed by daltoniam** 2017-12-09 04:04 UTC

**Comment by iandundas** [comment] 2018-01-25 21:45
@skerkewitz does this work on the device also? It works great for me on the simulator, but on device I see: 

> Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument" UserInfo={_kCFStreamErrorCodeKey=22, _kCFStreamErrorDomainKey=1}

Just wondering if it was intended to work (or maybe there's something amiss at my end).

Thanks

**Comment by iandundas** [comment] 2018-01-25 21:49
Using: 

```swift
            var request = URLRequest(url: url)
            request.timeoutInterval = 5
            let stream = FoundationStream()
            stream.enableSOCKSProxy = true

            let rawSocket: WebSocket = WebSocket(request: request, stream: stream)
```

**Comment by skerkewitz** [comment] 2018-01-26 09:56
@iandundas Nope, it does not work for me on a real device (iPhone 7, iOS 11.2.2). I get the same `Domain=NSPOSIXErrorDomain Code=22 "Invalid argument"` error.

It's actually what I expected because of the usage of `CFNetworkCopySystemProxySettings` as explained in an earlier post.

**Comment by psi-gh** [comment] 2018-07-03 10:33
I confirm it doesn't work on real device (ios12)

**Comment by phpmaple** [comment] 2018-07-19 08:47
error same to me

**Comment by sacred0x01** [comment] 2018-09-27 09:18
For now you can do something like this. Find `if enableSOCKSProxy {`  section and replace it with 
```swift
if enableSOCKSProxy {  
    let socksConfig = CFDictionaryCreateMutableCopy(nil, 0, CFNetworkCopySystemProxySettings()!.takeRetainedValue())
    let propertyKey = CFStreamPropertyKey(rawValue: kCFStreamPropertySOCKSProxy)
    let dict = socksConfig as? [String: Any]
    if let ip = dict?["HTTPSProxy"]  as? String, let port = dict?["HTTPSPort"] as? Int {
        let customSocksConfig = ["SOCKSProxy": ip, "SOCKSPort": port + 1, "SOCKSEnable": 1] as CFDictionary?
        CFWriteStreamSetProperty(outputStream, propertyKey, customSocksConfig)
        CFReadStreamSetProperty(inputStream, propertyKey, customSocksConfig)
    }
 }
```

To adjust socks proxy turn on in charles https & socks proxy simultaneously. Socks we will user to sniff the traffic, http proxy will help other network services work properly. And we will use default proxy setting UI in ios preferences.
Then  device proxy setting fill in with proper ip and http proxy port (eg 8888). Socks proxy port by default will listen on 8889 port.
On simulator all should work without any additional changes.

**Comment by dai-cb** [comment] 2018-11-22 13:51
Thanks, but sadly it doesn't work 😞

**Comment by sacred0x01** [comment] 2018-11-22 13:56
@dai-cb You did something wrong, because i am case it's working solution

**Comment by dai-cb** [comment] 2018-11-22 14:03
Is this on device? You can't set iOS proxy settings in Simulator.

**Comment by sacred0x01** [comment] 2018-11-22 15:02
@dai-cb It's in both case. Simulator uses proxy setting of mac os - so the computer which is running your simulator

**Comment by psi-gh** [comment] 2019-03-08 13:52
**sacred0x01**'s code is working for a device. Thanks! Didn't test on simulator yet.

**Comment by KonstantinEfimenko** [comment] 2020-04-21 14:07
This solution is not in work code now. But why? And how to intercept traffic by CharlesProxy from real device now?
