### ISSUE TITLE
Can't get Starscream to work in a simple command-line app

### ISSUE THREAD

**Issue by gmosx** [daltoniam/Starscream#254] opened 2016-09-25 10:25 UTC
I am playing with a simple command-line app:

`$ swift package init --type=executable`

After adding Starscream as a dependency, I added the following code in main.swift

```
import Foundation
import Starscream

let echoURL = URL(string: "ws://echo.websocket.org/")!

class WsClient: WebSocketDelegate {
    let socket: WebSocket

    init() {
        socket = WebSocket(url: echoURL)
        socket.delegate = self
    }

    func connect() {
        print("Connecting")
        socket.connect()
    }

    func websocketDidConnect(socket: WebSocket) {
        print("Connected")
        socket.write(string: "test") {
            print("Sent")
        }
    }

    func websocketDidReceiveData(socket: WebSocket, data: Data) {    
    }

    func websocketDidDisconnect(socket: WebSocket, error: NSError?) {
        print("Disconnect")
        print(error)
    }
    
    func websocketDidReceiveMessage(socket: WebSocket, text: String) {
    }
}

let client = WsClient()
client.connect()

sleep(10)
```

I build the app and run it.

```
$ swift build
$ ./build/.../TestApp
```

However the delegate methods are not called, i.e. I see "Connecting" printed but not "Connected" (or "Disconnected".

Any help appreciated.

PS: I am running on latest macOS with Swift 3.0

**Comment by daltoniam** [comment] 2016-09-26 04:46
The issue is using `sleep`. That blocks the main runloop from processing any of the delegate request that come back to it. Change the `sleep` to:

```swift
while(true) {
    RunLoop.current.run(until: Date())
    usleep(10)
}
```

This will achieve the "blocking" and keep the app from closing right on start, but still allow the runloop to process delegate callbacks.

**Comment by daltoniam** [comment] 2016-09-26 04:47
Full code for clarity:

```swift
import Foundation
import Starscream

let echoURL = URL(string: "ws://echo.websocket.org/")!

class WsClient: WebSocketDelegate {
    let socket: WebSocket
    
    init() {
        socket = WebSocket(url: echoURL)
        socket.delegate = self
    }
    
    func connect() {
        print("Connecting")
        socket.connect()
    }
    
    func websocketDidConnect(socket: WebSocket) {
        print("Connected")
        socket.write(string: "test") {
            print("Sent")
        }
    }
    
    func websocketDidReceiveData(socket: WebSocket, data: Data) {
    }
    
    func websocketDidDisconnect(socket: WebSocket, error: NSError?) {
        print("Disconnect")
        print(error)
    }
    
    func websocketDidReceiveMessage(socket: WebSocket, text: String) {
        print("Got: \(text)")
    }
}

let client = WsClient()
client.connect()

while(true) {
    RunLoop.current.run(until: Date())
    usleep(10)
}
```

**Closed by daltoniam** 2016-09-26 04:47 UTC

**Comment by gmosx** [comment] 2016-09-26 06:06
Duh!

Working with single-threaded languages for a long-time does this to you :)

Thank you!

**Comment by vhmth** [comment] 2018-04-02 03:34
@gmosx how did you get around missing dynamic link refs when building the executable? I'm getting these issues, and I believe it's because Swift has no good way of dealing with dynamic frameworks for commandline apps. Coacocapods introduced a way to specify a framework as static, but Starscream doesn't appear to conform in its Podspec

https://github.com/CocoaPods/CocoaPods/pull/6811
