### ISSUE TITLE
Using xcodeproj for tvOS projects

### ISSUE THREAD

**Issue by adamcooke** [daltoniam/Starscream#132] opened 2015-11-04 09:17 UTC
I seem to be having an issue with getting Starscream to work by adding the `xcodeproj` file to a tvOS application. Unfortunately, I'm quite new to Xcode so I'm not entirely sure what's wrong. 

Here's how to reproduce the issue using the latest version of Xcode.

1. Create new tvOS single view application
2. Clone starscream repo into application root
3. Drag the `Starscream.xcodeproj` into new application
4. Add `StarscreamTv` as an Embedded Binary (and Linked Framework)
5. Import `Starscream` at the top of the app delegate
6. Receive error `No such module 'Starscream'`

Here's some screenshots:

![Screenshot](https://s.adamcooke.io/15/BwK3nud6rM.png)

![Screenshot](https://s.adamcooke.io/15/VyNua91kJg.png)

**Comment by daltoniam** [comment] 2015-11-04 21:20
Thanks for the report. I think the issue is the product name setting didn't get changed when the new StarscreamTv target was added. I checked a fix into master for this. 

(Also you can just change the import to `import StarscreamTv` until you get the latest).

**Comment by adamcooke** [comment] 2015-11-04 22:22
No problem. I've just tested this out but it does still seem to be same (although the framework is now correctly called `Starscream.framework`). 

I think I tried importing `StarscreamTv` earlier but that also resulting the same not found error.

One error I have received (somewhat intermittently) is below. This was when running 756a4275.

```
warning: no umbrella header found for target 'StarscreamTv', module map will not be generated
```

**Comment by daltoniam** [comment] 2015-11-04 23:05
I created a testTV project. There was an issue with tvOS target didn't have any compile sources add to it :confused:. I checked in a fix to master should be good to go now.

**Comment by tyregor** [comment] 2015-11-05 07:57
Hi there, I had the same issue and tested the current commit. Sadly it still doesn't build with error log stating:

    Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvos9.0

    === BUILD TARGET StarscreamTv OF PROJECT Starscream WITH CONFIGURATION Release ===

    Check dependencies

    === BUILD TARGET StarscreamTvTests OF PROJECT Starscream WITH CONFIGURATION    Release ===

     Check dependencies

    ** BUILD SUCCEEDED **

    Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvsimulator9.0

    === BUILD TARGET StarscreamTv OF PROJECT Starscream WITH CONFIGURATION Release ===

    Check dependencies
     target 'StarscreamTv' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'appletvos' platform

So turning bitcode on and all is well?

**Comment by adamcooke** [comment] 2015-11-05 09:48
I can confirm the latest `master` works fine with the reproduction steps above. It also worked when building with a standard Release config so I'm not sure about the bitcode issue.

**Comment by tyregor** [comment] 2015-11-05 16:33
@adamcooke yeah, sorry. My bad the issue I'm having only presents itself if building with carthage. Although it would be nice if that'll work too.

**Comment by daltoniam** [comment] 2015-11-05 18:05
@adamcooke good to hear, thanks for the feedback. @tyregor That should be resolved in master now. I did the Carthage bit code fix for the iOS project, but hadn't done it for the TV one. I will release a new tag shortly as well `1.0.2`.

**Closed by daltoniam** 2015-11-05 18:05 UTC
