### ISSUE TITLE
Phone hang when try to reconnect iOS 7

### ISSUE THREAD

**Issue by sandeepsuthar** [daltoniam/Starscream#201] opened 2016-06-02 08:25 UTC
I am using swift library on iOS 7.1 with iPhone 4s . Everything working fine but when my DSL network down and my app try to reconnect then app hang for few second .This happen only with this device and OS . I have manually try to reconnect after 5 second to web socket  when it disconnected .

**Comment by acmacalister** [comment] 2016-06-03 03:46
What version of Starscream are you running? Do you have any example code to reproduce this? There are a number of networking related issues that could the socket or app to "hang".

**Comment by sandeepsuthar** [comment] 2016-06-03 05:36
I am using last release of swift version and this happens  only in swift library and jetfire running well.
iPhone will hang when my DSL network is down but wifi is available , in this case websocket try to connect but it faile with error "write wait timeout".
When i  read your websocket code then i think problem was at following line:
while !outStream.hasSpaceAvailable {
                usleep(100) //wait until the socket is ready
                out -= 100
                if out < 0 {
                    self?.cleanupStream()
                    self?.doDisconnect(self?.errorWithDetail("write wait timed out", code: 2))
                    return
                } else if outStream.streamError != nil {
                    return //disconnectStream will be called.
                }
            }
when i commented these line and  put only below line in block then code works perfectly in iOS 7 with 4S device.Now my block look like this
writeQueue.addOperationWithBlock { [weak self] in
            /*while !outStream.hasSpaceAvailable {
                usleep(100) //wait until the socket is ready
                out -= 100
                if out < 0 {
                    self?.cleanupStream()
                    self?.doDisconnect(self?.errorWithDetail("write wait timed out", code: 2))
                    return
                } else if outStream.streamError != nil {
                    return //disconnectStream will be called.
                }
            }*/
            outStream.write(bytes, maxLength: data.length)
        }
 These above commented lines absent in jetfire and above iOS 7 and on iPad is works properly.
thnx

**Comment by daltoniam** [comment] 2016-06-03 18:00
Ah ok, yeah I think you are hitting a timeout. Try upping the timeout variable:
```
socket.timeout = 60
```

**Comment by sandeepsuthar** [comment] 2016-06-04 11:05
I used this but app still not working when connection timeout. Please give some idea to solve this

**Comment by daltoniam** [comment] 2016-06-07 05:45
Hm, I'm not sure what you are seeing then. Those lines included in Starscream ensure the socket is ready to be used before it attempts writing to it. If changing the timeout didn't seem to help, you must be seeing something else. If there is any example code or a project you can share that would help troubleshooting.

**Comment by daltoniam** [comment] 2016-07-09 06:02
I am going to close this out. We will reopen once we get a example project. Thanks!

**Closed by daltoniam** 2016-07-09 06:02 UTC

**Comment by sandeepsuthar** [comment] 2016-09-27 10:11
Is it sufficient to send .xccrashpoint  file from Xcode ? I am running app from Test Flight.

**Comment by daltoniam** [comment] 2016-09-30 18:14
That depends on if the `.xccrashpoint` is symbolicated. If not, doesn't really help narrow since we don't what line is crashing. I also might try update to the latest code, this issue is quite old, might already be resolved in a newer release.
