### ISSUE TITLE
Crash when the server frame size is too large

### ISSUE THREAD

**Issue by ayking** [daltoniam/Starscream#182] opened 2016-03-31 06:49 UTC
We encounter a problem that when the server set the frame size to 1MB and send a single large message (20MB) to the mobile client then it will crash due to use up all the memory (Instruments show it consumed 2.8GB). but when after increase the BUFFER_MAX (from 4096 to 16384) in WebSocket the memory issues seems solved. Can you help verify this problem?

**Comment by daltoniam** [comment] 2016-03-31 19:33
Ok. Thanks for the information. Is there a test project you could provide that I can reproduce this with?

**Comment by ayking** [comment] 2016-04-04 12:32
Please try to connect this testing server with latest version Starscream.

https://github.com/ayking/Starscream-memory-issue-test-server

**Comment by daltoniam** [comment] 2016-04-10 03:29
Thank you much. I will try and debug this ASAP.

**Comment by daltoniam** [comment] 2016-05-17 05:22
Finally got a moment to look at this. I just checked in a fix to the master branch that I think may help with big payloads like this. Please let me know if the latest in master fixes the issue. Thanks!

**Comment by acmacalister** [comment] 2016-06-15 06:04
Closing for now. If the issue is still occurring with the fixes in master we can reopen this.

**Closed by acmacalister** 2016-06-15 06:04 UTC
